# -*- coding: utf-8 -*-
"""Model deployment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yzNROxY22vZR7kUwTgm2_YNWift1TY8n
"""


import streamlit as st
import tensorflow as tf

@st.cache(allow_output_mutation=True)
def load_model():
  model=tf.keras.models.load_model('cnn_model(1)')
  return model
model=load_model()
st.write("""
# Braille Detection System"""
)
file=st.file_uploader("Choose Braille photo from computer",type=["jpg","png"])
import cv2
from PIL import Image,ImageOps
import numpy as np
def import_and_predict(image_data,model):
    size=(28,28)
    image=ImageOps.fit(image_data,size,Image.ANTIALIAS)
    img=np.asarray(image)
    img_reshape=img[np.newaxis,...]
    prediction=model.predict(img_reshape)
    return prediction
if file is None:
    st.text("Please upload an image file")
else:
    image=Image.open(file)
    st.image(image,use_column_width=True)
    prediction=import_and_predict(image,model)
    class_names=['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 
                 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 
                 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 
                 'Y', 'Z']
    string="OUTPUT : "+class_names[np.argmax(prediction)]
    st.success(string)
